name: Build Geode Mod
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Android32
          os: ubuntu-latest
          target: Android32
        - name: Android64
          os: ubuntu-latest
          target: Android64
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch PersistenceAPI from Geode index
        shell: bash
        run: |
          curl -fL -o "$RUNNER_TEMP/persistenceapi.zip" 'https://api.geode-sdk.org/v1/mods/sabe.persistenceapi/versions/1.2.0/download'

      - name: Extract in geode-deps
        shell: bash
        run: |
          mkdir -p build/geode-deps/sabe.persistenceapi
          7z x "$RUNNER_TEMP/persistenceapi.zip" -o./build/geode-deps/sabe.persistenceapi
          echo '{ "required": true }' > build/geode-deps/sabe.persistenceapi/geode-dep-options.json

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          cli: "latest"
          target: ${{ matrix.config.target }}
          build-config: Release

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        id: build
      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
